### ISSUE TITLE
How to setup data and options?

### ISSUE THREAD

**Issue by jjoao07** [lon-yang/ngx-select2#1]
Hi @lon-yang 

Can you please help me, explaining how to setup data and options inside components and bind to ngx-select2 on template, if possible with dynamic data from Api

The point i have looked all code, but I can't see any example how to use it to pass data to ngx-select.

I have setted up, everything is working fine, but I don't know how i can pass data to ngx-select

this is what i got inside my component:
` <l-select2 [(ngModel)]="selected" formControlName="gender" [data]="data" [options]="options" [disabled]="false"></l-select2>`

and Inside of my component i tried setting data and options like this:

```
data:Array<any>;

options: any = [
        {uuid:1,name:'Male'},
        {uuid:2,name:'Female'}
        ];
```

But nothing is working, im still getting  No results found.

Can you assist me please, if you don't mind.

**Comment by lon-yang** [comment]
The data must hava `id` and `text` property. So it's like this
```js
data:Array<any> = [ { id: 'A', text: 'This is A' }, { id: 'B', text: 'This is B' }]
```
> Tips: If you want to change the `data` dynamic, you must change the reference

If you want to get data from remote api, you should set the `ajax` in `options`, e.x.
```js
options: any = {
   ajax: {
      url: 'your api address',
      dataType: 'json',
      ......
   }
}
```
You can see it at https://select2.github.io/options.html#ajax

**Comment by jjoao07** [comment]
hi @lon-yang 
Thanks, 
Just solved it!
this what i got on my code, in case someone else come with same problem.

Interface 
`export interface IGender {
    id:string;
    text:string;
}`
service
` getGender(){
        return this.http.get<IGender>(this.settings.api+'web/gender')
                    .catch(this.helper.handleServerError);
    }`
component
```
data: IGender[] = [];
    options: any = {};
 getGender(){
        return this.gender.getGender().subscribe(res =>{
            this.data = res;
        }, err =>{console.log(err)
        },()=>{'complete'});
    }
```

Template
`<l-select2 [(ngModel)]="selected" formControlName="gender" [data]="data" [options]="options"></l-select2>`

**Comment by jjoao07** [comment]
Hi @lon-yang 
I'm stuck for something else!

How do we get selected values, like when updating a form.

I can see that inside you got [(ngModel)]="elected" and i'm trying to set this value inside my component class, but doesn't work.

Also I checked your code, and i find out that you have selectedValue property.
So how do i populate default or selected value with ngx-select2

this what tried settig selected or selectedValue

`selectedValue:any = ['5fe2555b-f201-4165-8845-115039221463'` didn't work


`selected:any = {text: "Male", id: "5fe2555b-f201-4165-8845-115039221463"};` also didn't work

`selectedValue:any = {text: "Male", id: "5fe2555b-f201-4165-8845-115039221463"};` also din't work.

but the funny thing is that, if i setup `selected:any` and then console.log(this.selected)
I can get the selected values, i just can't figure out how to set it default values or selected inside of my component class

**Comment by lon-yang** [comment]
Like this http://lon-yang.github.io/ngx-select2/ ?

The demo code https://github.com/lon-yang/ngx-select2/blob/master/demo/src/app/app.component.ts

**Comment by jjoao07** [comment]
Thanks @lon-yang ,

I will implements and come back with feedback.

**Comment by jjoao07** [comment]
Hi @lon-yang 

I have been busy this days, that's why i never come back with any feedback.

and today i went through to finish my task, and tested your demo which works well.

So the problem comes with reactive Forms, which throw any error 
which throw error 
`Cannot read property 'val' of undefined`

![screen shot 2017-08-11 at 2 56 22 am](https://user-images.githubusercontent.com/19816874/29212239-bb5657fa-7e9d-11e7-8356-8ae40ee8ce84.png)

so my form is something like the code below:

```
<form [formGroup]="productForm" (ngSubmit)="addProduct($event, productForm.value)" novalidate autocomplete="off">

 <l-select2 [(ngModel)]="selected" formControlName="category_uuid" required name="category_uuid" [data]="categories" [options]="options"></l-select2>

</form>
```
so the code below does work, but if i change the form

```
<form novalidate #productForm="ngForm" (ngSubmit)="save(productForm)">

 <l-select2 [(ngModel)]="selected" formControlName="category_uuid" required name="category_uuid" [data]="categories" [options]="options"></l-select2>

</form>
```
So I'm not sure if you have tested it with reactive forms, or the bug is just on my side.

Please let me know if you have any idea how to use reactive forms with angular FormBuilder!

Regards

**Comment by lon-yang** [comment]
It's a bug. I find the `ngAfterViewInit` function not fired when using reactive forms. I will check this

**Comment by jjoao07** [comment]
Okay,

Please let me know if you find a solution, also i will keep trying on my side, if i get any solution
i will post out and let you know!

**Comment by jjoao07** [comment]
Hi @lon-yang 

Just solved it now, the solution is really easy, but you have helped on thinking about it.
this the solution you mentioned above.
 **I find the ngAfterViewInit function not fired when using reactive forms.** 

So what i have done inside component, i have imported AfterViewInit

`import { Component,AfterViewInit, OnInit } from '@angular/core';`

```
ngOnInit(){
//I initialize the data like the example of female and Male
 this.categories = [
      { text: 'Male', id: '5fe2555b-f201-4165-8845-115039221463' },
      { text: 'FeMale', id: 'ca22406c-350a-49e5-b0db-2714b164c560' }
    ];
}
```

and on view init i got the selected

```
ngAfterViewInit(){
        this.selected = [{ text: 'FeMale', id: 'ca22406c-350a-49e5-b0db-2714b164c560' }];
    }
```

So everything working fine.

**Comment by lon-yang** [comment]
There's a bug here and i had fixed it. Please use version `0.1.0`

**Comment by ctung** [comment]
I had some difficulty figuring out how to preset the defaults if the options are coming from ajax, but the selected defaults are coming from an Angular service.  Adding my solution here to save others time.  The basic summary is when your service returns the observable of the selected options, make a static copy of those selected options, and use the *ngFor directive to add those options to the select.

It seems like there should be a way to build this functionality directly into ngx-select2?

template:
```html
<l-select2 name="owners"  [(ngModel)]="feature.owners" [options]="ownerOptions">
  <option selected *ngFor="let owner of snapshot.owners" [value]="owner.id">{{owner.text}}</option>
</l-select2>
```

component.ts:

```typescript
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Feature } from '../feature';
import { FeatureService } from '../feature.service';

@Component({
  selector: 'app-feature-edit',
  templateUrl: './feature-edit.component.html',
  styleUrls: ['./feature-edit.component.css'],
})
export class FeatureEditComponent implements OnInit {
  feature: Feature;
  snapshot: Feature;

  ownerOptions = {
    multiple: true,
    minimumInputLength: 1,
    ajax: {
      url: "http://my_rest_server.com/rest/api/users",
      dataType: 'json',
      delay: 250,
      data: function (params) {
        return {
          q: params.term,
          page: params.page
        };
      },
      cache: true
    }
  }

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private featureService: FeatureService
  ) { }

  ngOnInit() {
    const id = this.route.snapshot.paramMap.get('id');
    this.featureService.getFeature({ _id: id })
      .subscribe(f => {
        this.feature = f;
        this.snapshot = JSON.parse(JSON.stringify(f)); // initial snapshot deep copy
      });
  }
}
```

**Comment by lon-yang** [comment]
I can try it
