### ISSUE TITLE
is this module supported angular onValueChange event?

### ISSUE THREAD

**Issue by joshi-anshul** [lon-yang/ngx-select2#20]
Hi,

I want to execute API on keyup, so added formControl attr, but its not working.

In HTML file:
`<l-select2 [formControl]="memberControl" required name="memberControl" [data]="users" (focus)="onFocusUsersInput()"></l-select2>`

In .ts file:
					`this.memberControl.valueChanges.pipe(
						debounceTime(300),
						tap(() => {
console.log('value change event!!');
						})
					)`

`public onFocusUsersInput(): void {
  console.log('here!!');      
}`

but nothing working

I want dynamically fetch data from the server, could you please help?

**Comment by lon-yang** [comment]
![2](https://user-images.githubusercontent.com/9428909/87738075-293ab780-c80f-11ea-8840-4eb6d7fd29fc.gif)

Please see this demo, https://stackblitz.com/edit/ngx-select2-issue-20 

I think it's working fine.

**Comment by joshi-anshul** [comment]
Hello @lon-yang 

Thanks for the response.
But I want functionality similar like this: [https://select2.org/data-sources/ajax](https://select2.org/data-sources/ajax)

but with respect to angular code standards
could you please let me know that is this possible in "ngx-select2"

Thanks

**Comment by lon-yang** [comment]
Got it. I have updated the stackblitz demo. You can pass the select2 option via `options` input.

**Comment by joshi-anshul** [comment]
Thanks @lon-yang 
But it's not follow the Angular standards, in example we are using ajax call but I need to get data using angular service and using observables.

 It would be highly appreciable, if you update example using angular service and observables.

Thanks in advance

**Comment by lon-yang** [comment]
Oh, I know what you mean. But unfortunately, select2 it's not support this feature for now with default data adapter.

**Comment by joshi-anshul** [comment]
Ok thanks @lon-yang
