### ISSUE TITLE
Placeholder not displayed if there are items in data array

### ISSUE THREAD

**Issue by dpalinic** [lon-yang/ngx-select2#3]
Hi @lon-yang,

Thanks for developing this library. I would like to report a small bug.

**Actual behavior:**
When there are items in data array, placeholder is not displayed but first item is selected automatically. Placeholder is displayed if `X` clear button is clicked.

**Expected behavior:**
When there are items in data array, placeholder should be displayed anyway and no items should be selected automatically. Placeholder is displayed again if `X` clear button is clicked.

**Code:**

```
@Component({
  selector: 'app-trip-list',
  templateUrl: './trip-list.component.html',
  styleUrls: ['./trip-list.component.scss']
})
export class TripListComponent implements OnInit {

  data: any = [{ id:'x', text: 'x' }, { id:'y', text: 'y' }];
  options: any = {
    theme: 'bootstrap',
    placeholder: 'Select a Line to show the Trips',
    allowClear: true
  };
  constructor() { }

  ngOnInit() {
  }

}
```

```
<l-select2 [(ngModel)]="selected" [data]="data" [options]="options" ></l-select2>
```

Thank you

**Comment by lon-yang** [comment]
I will check this

**Comment by risleylima** [comment]
Hi @dpalinic, 

This is a issue with the Select2 Library. 

I don't have the link of this issue to place here now, but to make the placeholder to show, you have to put an empty option on the init of the data.

In your example, it will be:

**Code:**
```typescript
@Component({
  selector: 'app-trip-list',
  templateUrl: './trip-list.component.html',
  styleUrls: ['./trip-list.component.scss']
})
export class TripListComponent implements OnInit {

  data: any = [{id:'',text:''},{ id:'x', text: 'x' }, { id:'y', text: 'y' }];
  options: any = {
    theme: 'bootstrap',
    placeholder: 'Select a Line to show the Trips',
    allowClear: true
  };
  constructor() { }

  ngOnInit() {
  }

}
```

Try to add that empty option on the init of the data and test if it will work.

**Comment by dpalinic** [comment]
Thank you very much @risleylima for the clarification. Regards.

**Comment by lon-yang** [comment]
So, I will close this issue
