### ISSUE TITLE
Change event not working on ngx-select2

### ISSUE THREAD

**Issue by indranshastri** [lon-yang/ngx-select2#7]
I am working with this component and need the select2 for populating another select2 i need change value event 
```
<l-select2 
                                        formControlName="data" 
                                        [data]="data" 
                                        [options]="{placeholder: 'Select something','val':0}" 
                                        [disabled]="false"
                                        (valueChanged)="getAnotherData($event)"
                                        >

                                        </l-select2>
```
but 

`(valueChanged) and (change)` event is not working 

please help to resovle the issue i tiried but not resolving

**Comment by lon-yang** [comment]
Try this `(ngModelChange)="getAnotherData($event)"`

**Comment by lon-yang** [comment]
I have added `valueChange` on version `0.2.0`. And it's support angular6. Please try this.
https://stackblitz.com/edit/angular-3oqqmt?file=src%2Fapp%2Fapp.component.ts
