### ISSUE TITLE
Reload component after load data 

### ISSUE THREAD

**Issue by patrycze** [lon-yang/ngx-select2#8]
Hey!!! is it possible to reload component data manualy? i have reference to component by 
  `<l-select2 #select2 ...`  `@ViewChild('select2') select2; ` and now i need reloading - i guess, because when i look at `LSelect2Component ` i see there my data but is not displayed . somewhere i read about `.trigger('change.select2'); ` but i'm not sure is it good approach, best regards!!! :-)

**Comment by lon-yang** [comment]
Change the `data` input will auto reload data for component. But the change must be the value not the reference value. Otherwise this will not trigger the `ngOnChanges` event, and the component will not reload the data too.
